import Head from 'next/head';
import NavBar from '../components/NavBar';
import SlideShow from '../components/SlideShow';
import { useState } from 'react';
import CvComponent from '../components/CvComponent';
import NavBarCv from '../components/NavBarCv';

export default function Cv() {
  const [bio, bioChange] = useState(false);
  const [menu, changeMenu] = useState(false);
  return (
    <>
      <Head>
        <title>trenton teinert</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <NavBarCv
          bio={bio}
          bioChange={bioChange}
          menu={menu}
          changeMenu={changeMenu}
        />
      </div>
      <div
        className={
          menu
            ? `relative transition-all ${
                bio ? 'mt-32' : 'mt-[2.7rem]'
              } md:mt-1 ml-4  md:ml-60 mr-4`
            : 'relative transition-all mt-1 ml-4 mr-4'
        }
      >
        <CvComponent />
      </div>
    </>
  );
}
