import Head from 'next/head';
import NavBar from '../components/NavBar';
import SlideShow from '../components/SlideShow';
import { useState } from 'react';
import CvComponent from '../components/CvComponent';
import NavBarCv from '../components/NavBarCv';

export default function Cv() {
  const [bio, bioChange] = useState(false);
  const [menu, changeMenu] = useState(false);
  return (
    <>
      <Head>
        <title>trenton teinert</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <NavBarCv
          bio={bio}
          bioChange={bioChange}
          menu={menu}
          changeMenu={changeMenu}
        />
      </div>
      <div
        className={
          menu
            ? 'md:absolute h-[85vh] w-[93%] md:w-[500px] text-justify transition-all duration-300 mt-2 md:mt-10 ml-4 md:ml-60'
            : 'md:absolute h-[85vh] w-[93%] md:w-[500px] text-justify transition-all duration-300 mt-2 md:mt-10 ml-4'
        }
      >
        <CvComponent />
      </div>
    </>
  );
}
