import Head from 'next/head';

import { useState } from 'react';
import CvComponent from '../components/CvComponent';
import NavBarCv from '../components/NavBarCv';

export default function Cv() {
  const [bio, bioChange] = useState(false);
  const [menu, changeMenu] = useState(false);
  return (
    <>
      <Head>
        <title>trenton teinert</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <NavBarCv
          bio={bio}
          bioChange={bioChange}
          menu={menu}
          changeMenu={changeMenu}
        />
      </div>
      <div
        className={
          menu
            ? `relative max-w-[600px] text-justify transition-all ${
                bio ? 'mt-[145px]' : 'mt-10'
              } md:mt-1 ml-[5%] md:ml-60 mr-[5%]`
            : `relative max-w-[600px] text-justify transition-all mt-2 md:mt-1 ml-[5%] md:ml-4 mr-[5%]`
        }
      >
        <CvComponent />
      </div>
    </>
  );
}
