import Head from 'next/head';
import NavBar from '../components/NavBar';
import { Inter } from '@next/font/google';
import SlideShow from '../components/SlideShow';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [menu, changeMenu] = useState(false);
  return (
    <>
      <Head>
        <title>trenton teinert</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='absolute'>
          <NavBar menu={menu} changeMenu={changeMenu} />
        </div>
        <div>
          <SlideShow menu={menu} changeMenu={changeMenu} />
        </div>
      </main>
    </>
  );
}
